app/routes/auth.py
from flask import Blueprint, request, redirect, session, render_template_string, flash
from app.models import get_user_by_email, create_user, verify_password, set_user, new_message
from app.errors import invalid_email, invalid_password, user_exists

auth_blueprint = Blueprint('auth', __name__)

@auth_blueprint.route('/register', methods=['POST'])
def register():
  email = request.form.get('email', '')
  user = get_user_by_email(email)
  if user:
    user_exists(email)
  else:
    create_user(email, request.form.get('password'))
    set_user(get_user_by_email(email))
  return redirect(request.referrer)

@auth_blueprint.route('/login', methods=['POST'])
def login():
  email = request.form.get('email', '')
  user = get_user_by_email(email)
  if user:
    if verify_password(user['password'], request.form.get('password', '')):
      set_user(user)
    else: invalid_password()
  else: invalid_email(email)
  return redirect(request.referrer)

@auth_blueprint.route('/logout', methods=['GET'])
def logout():
  session.pop('user', None)
  return redirect(request.referrer)

@auth_blueprint.route('/dashboard', methods=['GET'])
def dashboard():
  return render_template_string('Dashboard Coming Soon...')

app/templates/components/about-preview.html
<div class="space column center max-width row-10">
	<h3 class="magenta">Get To Know Me</h3>
	<p>
    I discovered my passion for web development in 1998 when I first learned HTML and later helped improve my school district’s web pages. Over the years, I built an eCommerce site, earned a MERN stack certification, and kept honing my skills through hands-on projects. Now, I’m focused on continuous learning and developing my own Python web framework.
  </p>
	<a href="/about" class="link-light">Read More...</a>
</div>

app/templates/components/demo-disclaimer.html
<div class='section-teal' id="demo-disclaimer">
	<div class="section-content row-10 column acenter max-width {% if closed %}closed{% endif %}">
		<h3>Demo Disclaimer</h3>
		<a href="#" class="link-light bold">
			{% if closed %}
				Show More
			{% else %}
				Show Less
			{% endif %}
		</a>
		<p class="small">
			The projects and applications showcased on this portfolio are for demonstration purposes only. These live demos are intended to highlight my skills and capabilities as a developer. Some demos may include basic authorization features, such as user profiles to track scores, statistics, and progress. These profiles are for simulation purposes only and can be accessed at any time by the user.
		</p>
		<p class="small">
			To ensure security, users are advised not to use common or personal passwords when interacting with these demos. You are welcome to use fake email addresses for testing purposes, as no email verification or real-world communication will occur.
		</p>
		<p class="small">
			No sensitive data should be submitted, and no data collected through these demos is used for monetary or commercial purposes. While every effort is made to provide a secure experience, the applications are not intended for real-world deployment. Please use them responsibly and with the understanding that they are works in progress.
		</p>
		<script>
			element = document.querySelector('#demo-disclaimer').children[0]
			link = element.querySelector('a')
			link.onclick = (e) => {
				e.preventDefault()
				element.classList.toggle('closed')
				const show = 'Show '
				link.innerText = show + ['More', 'Less'].filter(text => text != link.innerText.replace(show, ''))[0]
			}
		</script>
	</div>
</div>

app/templates/components/footer.html
<footer class="section-magenta">
	<div class="section-content row-20 flip jcenter">
		<div class="row-10 column acenter">
			<p class="small">
				I'm a web developer working with Python and JavaScript, building functional and user-friendly applications. I'm focused on always learning and exploring new technologies to improve my craft. Based in Central NJ.
			</p>
			<p class="small">
				This website is running on a Flask web server, with its built-in template engine. The data is managed through PyMongo. All other content, except where noted otherwise, has been created and developed by me.
			</p>
		</div>
		<div class="row-10 column acenter bold fit wrap unflip">
			<a href="/" class="link-teal small">Home Page</a>
			<a href="/projects" class="link-teal small">My Projects</a>
			<a href="/about" class="link-teal small">About Me</a>
			<a href="/contact" class="link-teal small">Contact Information</a>
			<a href="/quiggle" target="_blank" class="link-yellow small">Quiggle</a>
		</div>
		<div class="row-10 column acenter fit">
			<p class="small">c. 2025, by Jason Thompson</p>
			<a href="http://github.com/jake-the-cake" target="_blank" class="link-light small">Github</a>
			<a href="http://linkedin.com/in/ask-jake-thompson" target="_blank" class="link-light small">LinkedIn</a>
			<div class="row-05">
				Socials
			</div>
		</div>
	</div>
</footer>

app/templates/components/github-promo.html
<div class="space row-20 column">
    <h3 class="yellow">Visit My Github</h3>
    <p>
			A time capsule of my journey, starting in 2020 with the MERN stack and culminating in the ongoing development of a Python web framework.
		</p>
    <a href="https://www.github.com/jake-the-cake" target="_blank">
        <button class="button btn-yellow">Go To Github</button>
    </a>
</div>

app/templates/components/login-app.html
<div id="change-form" class="space column center max-width">
	<h3 class="teal">Login Widget</h3>
	<span class="note">
		this is a login widget.
	</span>
    <p class="status">
        {% if not user %}
            You Are Not Logged In
            <span>(Not Required)</span>
        {% elif user.get('error') %}
            {{ user['error'] }}
        {% else %}
            Logged in as: {{ user.email }}
        {% endif %}
    </p>
    {% if user and not user.error %}
    <div class="row-10 jcenter">
        <a href="{{ url_for('auth.dashboard') }}">
            <button class="btn-teal">Dashboard</button>
        </a>
        <a href="{{ url_for('auth.logout') }}">
            <button class="btn-teal-outline">Logout</button>
        </a>
    </div>
    {% else %}
        <div class="row-10 jcenter can-shrink">
            <button class="btn-yellow">Login</button>
            <button class="btn-magenta">Register</button>
        </div>
        {% include 'forms/login.html' %}
        {% include 'forms/register.html' %}
        <script src="{{ url_for('static', filename='js/apps/change-form.js') }}"></script>
    {% endif %}
</div>

app/templates/components/navbar.html
<nav class="section-content row-10 jcenter">
  <a href="/">
      <button class="btn-teal">Home</button>
  </a>
  <a href="/about">
      <button class="btn-teal">About</button>
  </a>
  <a href="/projects">
      <button class="btn-teal">Projects</button>
  </a>
  <a href="/contact">
      <button class="btn-teal">Contact</button>
  </a>
</nav>
<script src="{{ url_for('static', filename='js/nav-buttons.js') }}" defer></script>

app/templates/components/project-list.html
{% for project in projects %}
<div class="project-card">
	<div class="row-10">
		<img src="{{ project.img }}" alt="Sample Image">
		<div class="column">
			<div class="title">{{ project.title }}</div>
			<div class="desc">{{ project.desc }}</div>
			<a href="{{ project.url }}">View Demo</a>
		</div>
	</div>
</div>
{% endfor %}

app/templates/components/projects-promo.html
<div class="space row-10 column center max-width">
	<h3 class="yellow">See My Work</h3>
  <p>
    Explore my projects to see my approach to problem-solving, efficiency, and design in action. Each one is a demonstration of my skills, creativity, and continuous growth as a developer.
  </p>
  <a href="/projects" class="link-light">My Projects</a>
</div>

app/templates/components/social-links.html
<div class="section-magenta" id="social-media">
	<div class="section-content row-20 column acenter max-width">
		<h3 class="light">Social Media Links</h3>
		<p>
			If you're curious about my work or want to reach out, these links lead the way.
		</p>
		<div class="row-10 jcenter">
			<a href="http://github.com/jake-the-cake" target="_blank">
				<button class="btn-yellow-outline">Github</button>
			</a>
			<a href="http://linkedin.com/in/ask-jake-thompson" target="_blank">
				<button class="btn-teal-outline">LinkedIn</button>
			</a>
		</div>
		<div class="row-10 jcenter">
			Social buttons
		</div>
	</div>
</div>