app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify, session
from .forms import RegistrationForm, LoginForm
from .models import get_user_by_email, create_user, verify_password
from . import mongo

auth_blueprint = Blueprint('auth', __name__)
pages_blueprint = Blueprint('pages', __name__)

def use_login_form() -> LoginForm:
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = get_user_by_email(email)
        if user and verify_password(user['password'], password):
            session['user'] = user
        else:
            session['user'] = { 'error': 'Invalid login credentials.' }
        return redirect(request.referrer)  # Define a dashboard route later
    return form

@pages_blueprint.route('/about')
def about():
    return render_template('index.html')

@pages_blueprint.route('/contact')
def contact():
    return render_template('index2.html')

@pages_blueprint.route('/projects', methods=['GET', 'POST'])
def projects():
    user = session.get('user', None)
    print(user)
    register = RegistrationForm()
    return render_template('projects.html', login=use_login_form(), register = register, user=user)

@pages_blueprint.route('/')
def home():
    return render_template('home.html')

# routes requiring auth validations
@auth_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        
        if get_user_by_email(email):
            flash('Email is already registered.', 'danger')
        else:
            create_user(email, password)
            flash('Registration successful! Please log in.', 'success')
            return redirect(url_for('auth.login'))
    
    return render_template('register.html', form=form)

@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    return render_template('login.html', form=use_login_form())

@pages_blueprint.route('/data')
def data():
    users = []
    for user in mongo.db.users.find():
        user['_id'] = str(user['_id'])
        users.append(user)
    return jsonify(users)

app/templates/forms/contact.html
<div class="space row-20 column acenter max-width" id="contact-form">
	<h3 class="teal">Send Me A Message</h3>
	{% with messages = get_flashed_messages() %}
		{% if messages|length > 0 %}
			{% for m in messages %}
			<p class="small">{{ m }}</p>
			{% endfor %}
		{% else %}
		{% if form.email.errors %}
			<p class="small">
				{% for error in form.email.errors %}
					{{ error }}
				{% endfor %}
			</p>
		{% endif %}
		<form class="row-20 column acenter" method="POST">
			{{ form.hidden_tag() }}
			<div class="column">
				{{ form.name.label }}
				{{ form.name }}
			</div>
			<div class="column">
				{{ form.email.label }}
				{{ form.email }}
			</div>
			<div class="column">
				{{ form.message.label }}
				{{ form.message(rows="6") }}
			</div>
			<div class="row-10 jcenter">
				{{ form.submit(class='btn-teal') }}
				<button class="no-btn link-teal" id="clear-form-button">Clear</button>
			</div>
		</form>
		<script>
			const form = document.querySelector('#contact-form').querySelector('form')
			const clearButton = form.querySelector('#clear-form-button')
			clearButton.addEventListener('click', (e) => {
				e.preventDefault()
				form.reset()
			})
		</script>
		{% endif %}
	{% endwith %}
</div>

app/templates/forms/login.html
<form method="POST" action="{{ url_for('auth.login') }}" id='login-form' class="row-10 column acenter shrinkY can-shrink max-column">
    {{ login.hidden_tag() }}
    <div class="column">
        {{ login.email.label }} {{ login.email }}
    </div>
    <div class="column">
        {{ login.password.label }} {{ login.password }}
    </div>
    <div class="row-10 jcenter">
        {{ login.submit(class='btn-yellow') }}
        <button id="login-cancel" class="no-btn link-yellow">Cancel</button>
    </div>
    <div class="small">No account? <span href="#" class="link-teal">Register Here</span></div>
</form>

app/templates/forms/register.html
<form method="POST" action="{{ url_for('auth.register') }}" id='registration-form' class="row-10 column acenter shrinkY can-shrink max-column">
    {{ register.hidden_tag() }}
    <div class="column">
        {{ register.email.label }} {{ register.email }}
    </div>
    <div class="column">
        {{ register.password.label }} {{ register.password }}
    </div>
    <div class="column">
        {{ register.confirm_password.label }} {{ register.confirm_password }}
    </div>
    <div class="row-10 jcenter">
        {{ register.submit(class='btn-magenta') }}
        <button id="register-cancel" class="no-btn link-magenta">Cancel</button>
    </div>
    <div class="small">Have an account? <span href="#" class="link-teal">Login Here</span></div>
</form>